[package]
name = "rust-companion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
iced = "0.10.0"
web-audio-api = "0.15.0"
